// ==========================================================================
// tools/encode-puzzles.js
// Regenerates data/puzzles.js (obfuscated) from data/puzzles.source.js.
//
// HOW TO USE:
//   1. Edit the readable master file:  data/puzzles.source.js
//   2. Run:  node tools/encode-puzzles.js
//   3. Deploy. Only data/puzzles.js (the encoded blob) is loaded by the page.
//
// NOTE: This is obfuscation, NOT encryption. It stops casual players from
// reading the answers in the inspector, but a determined user can still
// decode it in the console. For real protection the answers must be kept
// server-side (see the security notes). Do NOT deploy puzzles.source.js.
// ==========================================================================

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const root = path.resolve(__dirname, '..');
const sourcePath = path.join(root, 'data', 'puzzles.source.js');
const outPath = path.join(root, 'data', 'puzzles.js');

const sourceCode = fs.readFileSync(sourcePath, 'utf8');

// Evaluate the source in an isolated sandbox to extract the PUZZLES array.
const sandbox = {};
vm.createContext(sandbox);
vm.runInContext(sourceCode + '\n;this.__PUZZLES__ = PUZZLES;', sandbox);
const puzzles = sandbox.__PUZZLES__;

if (!Array.isArray(puzzles)) {
    console.error('Could not find a PUZZLES array in data/puzzles.source.js');
    process.exit(1);
}

const encoded = Buffer.from(JSON.stringify(puzzles), 'utf8').toString('base64');

const output = `// AUTO-GENERATED by tools/encode-puzzles.js - DO NOT EDIT BY HAND.
// Edit data/puzzles.source.js and re-run: node tools/encode-puzzles.js
const PUZZLES = (function () {
    const _d = "${encoded}";
    const json = decodeURIComponent(escape(atob(_d)));
    return JSON.parse(json);
})();
`;

fs.writeFileSync(outPath, output, 'utf8');
console.log(`Encoded ${puzzles.length} puzzles -> data/puzzles.js`);
